#include <iostream>
using namespace std;

class ExceptionHandler {
public:
    void demonstrateExceptions() {
        try {
            // Code that may throw exceptions
            int numerator, denominator, result;

            cout << "Enter numerator: ";
            cin >> numerator;

            cout << "Enter denominator: ";
            cin >> denominator;

            if (denominator == 0) {
                throw "Division by zero is not allowed.";
            }

            result = numerator / denominator;

            cout << "Result of division: " << result << endl;
        } catch (...) {
            // Catch block for handling all types of exceptions
            cerr << "An exception occurred." << endl;
        }
    }
};

int main() {
    ExceptionHandler handler;
    handler.demonstrateExceptions();

    return 0;
}

